# Generated by Django 6.1.1 on 2026-09-21 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Current year of study (1-6)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short profile summary or bio', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='branch_or_major',
            field=models.CharField(blank=True, help_text='Field of study (e.g. Computer Science, AIML, Mechanical)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='college_name',
            field=models.CharField(blank=True, help_text='Current university, institute, or college', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Expected or actual year of graduation (e.g. 2026)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_student',
            field=models.BooleanField(default=False, help_text="Designates whether the user's academic status has been verified."),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation_points',
            field=models.PositiveIntegerField(default=0, help_text='Points earned by uploading quality notes, resources, or helping others'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('EDUCATOR', 'Educator / Professor'), ('MODERATOR', 'Moderator')], default='STUDENT', help_text="User's primary role on StudyHub", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
