# Generated by Django 6.1.1 on 2026-09-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_college_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='degree',
        ),
        migrations.AddField(
            model_name='branch',
            name='degree',
            field=models.ManyToManyField(related_name='branches', to='academics.degree'),
        ),
    ]
